version: '3.3'
services:
  app:
    build: ./
    restart: always
    container_name: cloud_backend
    ports:
      - 9999:9999
    volumes:
      - $PWD/config.json:/app/config.json
      - $PWD/logs/:/app/logs/
      - $PWD/uploads/:/app/uploads/

  db:
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - $PWD/mysql:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: 
        MYSQL_DATABASE: 
  
  influx:
    image: influxdb:1.1.1
    ports:
      - 8086:8086
    volumes:
      - $PWD/influxdb/:/var/lib/influxdb/
    environment:
      - DOCKER_INFLUXDB_INIT_BUCKET=cloudDB
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER:-admin}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD:-admin}

  adminer:
    image: adminer
    restart: always
    ports:
      - 4040:8080
      - 8083:8083
    



    

